// Authoritative supplied biography: preserve every paragraph verbatim.
export const presidentBiography = [
  'Ejike Celestine Nnaji is a Nigerian social entrepreneur, business leader, youth development advocate, community development practitioner, and strategic communications professional with experience spanning entrepreneurship, public-sector engagement, student leadership, advocacy, strategic communication, and organisational development.',
  'He is the Chief Executive Officer of Celvia Koncept Ltd, President of Impact Youth Development Initiative (IYDI), and Convener of the Impact Business Innovation Summit, a platform focused on entrepreneurship, innovation, skills development, mentorship, investment opportunities, women empowerment, and inclusive economic development.',
  'Nnaji has held several leadership and public-sector positions, including Technical Assistant to His Excellency, Rt. Hon. Ifeanyi Lawrence Ugwuanyi, former Governor of Enugu State; Former National President of the National Union of Nkanu Students; and Former Public Relations Officer (PRO) of the National Association of Nigerian Students (NANS).',
  'He also served as Chief Press Secretary to the Chairman of ALGON, Enugu State Chapter; Chairman, ALGON South-East; and Deputy National Publicity Secretary, ALGON, where he gained extensive experience in strategic communications, media relations, stakeholder engagement, public information, and institutional advocacy.',
  'Through his leadership of IYDI and the Impact Business Innovation Summit, Nnaji continues to champion practical opportunities for young people and women by connecting them with skills, entrepreneurship, mentorship, innovation, partnerships, investment, and capacity-building opportunities.',
  'His leadership philosophy is anchored on service, integrity, innovation, empowerment, collaboration, and measurable impact. He is committed to building sustainable platforms and partnerships that empower young Nigerians to become entrepreneurs, innovators, leaders, employers, and active contributors to community and national development.',
];
export const presidentRoles = ['CEO, Celvia Koncept Ltd', 'President, Impact Youth Development Initiative', 'Convener, Impact Business Innovation Summit', 'Social Entrepreneur', 'Youth Development Advocate', 'Strategic Communications Professional'];
export const presidentCoreAreas = ['Youth Development', 'Entrepreneurship', 'Social Impact', 'Strategic Communications', 'Public Relations', 'Leadership', 'Community Development', 'Women Empowerment', 'Innovation', 'Stakeholder Engagement', 'Enterprise Development', 'Mentorship'];
// Set only when an official professional portrait has been supplied.
export const presidentPortrait: { url: string; alt: string } | undefined = undefined;