import { createFileRoute } from '@tanstack/react-router';
import { PageIntro, Purpose, Beneficiaries, JoinCTA } from '@/components/iydi-sections';
import { pageHead } from '@/lib/iydi-content';
import { objectives, coreValues } from '@/lib/iydi-details';
import logo from '@/assets/iydi-official-logo.webp.asset.json';

export const Route = createFileRoute('/about')({ head: () => pageHead('About the organization', 'Meet IYDI, a Nigerian youth-focused organization committed to empowering young people and women for sustainable development.'), component: About });
function About() {
  return <><PageIntro label="About IYDI" title="People. Potential. Purpose."><p>A Nigerian development organization with young people and women at the heart of its work.</p></PageIntro><section className="section"><div className="site-container about-grid"><img className="about-logo" src={logo.url} alt="Official Impact Youth Development Initiative logo" width="280" height="280" /><div><span className="eyebrow">Impact Youth Development Initiative</span><h2>Empowerment with<br />a shared purpose.</h2><p className="lead-copy">IYDI is committed to empowering young people and women to become productive, innovative, responsible and active contributors to sustainable community and national development.</p><p>Our focus connects skills, entrepreneurship, innovation, leadership, mentorship and opportunities. Across nine programme areas, we place people and their potential at the centre of development.</p></div></div></section>
    <section className="section purpose-section"><div className="site-container purpose-grid"><article><span className="eyebrow">Our purpose</span><h3>Learn. Innovate.<br />Build. Connect. Thrive.</h3><p>IYDI creates an enabling platform where young people and women can learn, innovate, build, connect and thrive.</p></article><article><span className="eyebrow">Our aim</span><h3>Independence.<br />Leadership. Livelihoods.</h3><p>To empower young people and women with knowledge, skills, opportunities, networks and resources for economic independence, responsible citizenship, leadership and sustainable livelihoods.</p></article></div></section>
    <section className="section"><div className="site-container"><Purpose /></div></section>
    <section className="section programmes-section"><div className="site-container"><div className="section-heading"><div><span className="eyebrow">Our objectives</span><h2>A clear commitment to development.</h2></div></div><div className="objective-grid">{objectives.map((item, index) => <article className="objective-item" key={item.title}><span className="objective-number">{String(index + 1).padStart(2, '0')}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></div></section>
    <section className="section"><div className="site-container"><div className="section-heading"><div><span className="eyebrow">Our core values</span><h2>What guides our work.</h2></div></div><div className="values-grid">{coreValues.map(value => <article className="value-item" key={value.title}><value.icon size={27} strokeWidth={1.4} /><h3>{value.title}</h3><p>{value.description}</p></article>)}</div></div></section>
    <section className="section aspiration-section"><div className="site-container narrow-content"><span className="eyebrow">Our long-term aspiration</span><h2>An African platform.<br />A lasting contribution.</h2><p className="lead-copy">IYDI aspires to become a leading African platform for youth and women empowerment, entrepreneurship, innovation, leadership development and community transformation.</p></div></section>
    <section className="section"><div className="site-container serve-grid"><div><span className="eyebrow">Who we serve</span><h2>Opportunity<br />for more people.</h2></div><Beneficiaries /></div></section><JoinCTA /></>;
}